version: "3"
services:
       qa-api:
           container_name: qa-api
           image: qaservice
           restart: always
           build: .
           ports:
             - "8080:8080"
           volumes:
             - ./:/code
           links:
             - qa-dbms
       qa-dbms:
             container_name: qa-dbms
             image: mongo:4.4.4
             environment:
              - MONGO_INITDB_DATABASE=qa-dbms
              - MONGO_INITDB_ROOT_USERNAME=root
              - MONGO_INITDB_ROOT_PASSWORD=rfp51-pineapple
             volumes:
               - ./mongodb:/data/db
             restart: always
             ports:
               - '27017:27017'
       mongo-seed:
         image: mongo:4.4.4
         links:
           - qa-dbms
           depends_on:
             - qa-dbms
             command: [
               "mongoimport --host qa-dbms"
             ]
volumes:
  mongodb:
