version: "3"
services:
       qa-api:
           container_name: qa-api
           image: qaservice
           restart: always
           ports:
             - "${PORT:3000}"
           volumes:
             - ./:/code
           links:
             - qa-dbms
       qa-dbms:
             container_name: qa-dbms
             image: mongo:4.4.4
             links: qa-api
             volumes:
               - ./mongodb:/data/db
               - ./:/code
             restart: always
             ports:
               - ${DBPORT:2018}
       mongo-seed:
         image: mongo:4.4.4
         links:
           - qa-dbms
           volumes:
             - ./:/code
           depends_on:
             - qa-dbms
             command: [
               "-f: unlimited -t: unlimited -v: unlimited [1] -l: unlimited -n: 64000 -m: unlimited [1] [2] -u: 64000",
               "mongoimport --username mongodb mongodb://${HOST}:${DBPORT:2018}/qa-dbms] --collection=products --mode=upsert --upsertFields=product_id --numInsertionWorkers=4 --file ${PRDATA}"
               "mongoimport --username mongodb mongodb://${HOST}:${DBPORT:2018}/qa-dbms] --collection=questions --mode=upsert --upsertFields=question_id --numInsertionWorkers=4 --file ${QDATA}", "mongoimport --username mongodb mongodb://${HOST}:${DBPORT:2018}/qa-dbms] --collection=answers --mode=upsert --upsertFields=answer_id --numInsertionWorkers=4 --file ${ADATA}", "mongoimport --username mongodb mongodb://${HOST}:${DBPORT:2018}/qa-dbms] --collection=photos --mode=upsert --upsertFields=photo_id --numInsertionWorkers=4 --file ${PDATA}"
             ]
volumes:
   - type: bind
   source: ../../.env
   target: ./.env
   read_only: true
  mongodb:
networks:
  default:
    external: true
    name: ${SECURITYGROUP}
